# Generated by Django 4.0.3 on 2022-04-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-likes']},
        ),
    ]
