# Generated by Django 4.0.3 on 2022-04-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
