# Generated by Django 4.0.3 on 2022-04-04 13:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_alter_comment_options_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images/'),
        ),
    ]
