# Generated by Django 4.0.3 on 2022-04-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_image_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='published_date',
        ),
    ]
